# Generated by Django 5.1.7 on 2025-03-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
