# Generated by Django 5.1.7 on 2025-03-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_alter_studentmodel_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
