# Generated by Django 5.1.7 on 2025-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_alter_studentmodel_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='student_course',
            field=models.CharField(choices=[('DS', 'Desenvolvimento de sistemas'), ('DDI', 'Design de interiores'), ('MEC', 'Mecânica'), ('CV', 'Comunicações visuais'), ('QUI', 'Química'), ('MAT', 'Médio/Matemática'), ('BIO', 'Médio/Biologia'), ('DG', 'Design gráfico'), ('ADM', 'Administração'), ('EDF', 'Edificações'), ('LOG', 'Logística')], default='DS', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student_grade',
            field=models.CharField(choices=[('1Y', '1° Ano'), ('2Y', '2° Ano'), ('3Y', '3° Ano')], default='3Y', max_length=2),
            preserve_default=False,
        ),
    ]
