# Generated by Django 5.1.7 on 2025-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0006_studentmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
