# Generated by Django 5.1.7 on 2025-03-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rm', models.CharField(max_length=5)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('biometry', models.CharField(blank=True, max_length=5)),
                ('is_in_school', models.BooleanField(default=False)),
            ],
        ),
    ]
