# Generated by Django 5.1.7 on 2025-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentmodel_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
